icons = {
    'alert-circle-outline': 0,
    'lightbulb': 1,
    'thermometer': 2,
    'gesture-tap-button': 3,
    'flash': 4,
    'music': 5,
    'check-circle-outline': 6,
    'close-circle-outline': 7,
    'pause': 8,
    'play': 9,
    'palette': 10,
    'window-open': 11,
    'weather-cloudy': 12,
    'weather-fog': 13,
    'weather-hail': 14,
    'weather-lightning': 15,
    'weather-lightning-rainy': 16,
    'weather-night': 17,
    'weather-partly-cloudy': 18,
    'weather-pouring': 19,
    'weather-rainy': 20,
    'weather-snowy': 21,
    'weather-snowy-rainy': 22,
    'weather-sunny': 23,
    'weather-windy': 24,
    'weather-windy-variant': 25,
    'water-percent': 26,
    'power': 27,
    'fire': 28,
    'calendar-sync': 29,
    'fan': 30,
    'snowflake': 31,
    'solar-power': 32,
    'battery-charging-medium': 33,
    'battery-medium': 34,
    'shield-home': 35,
    'door-open': 36,
    'door-closed': 37,
    'window-closed': 38,
    'shield-off': 39,
    'shield': 40,
    'shield-lock': 41,
    'shield-airplane': 42,
    'bell-ring': 43,
    'ray-vertex': 44,
    'script-text': 45,
    'home-import-outline': 46,
    'home-export-outline': 47,
    'arrow-up-bold': 48,
    'arrow-down-bold': 49,
    'cast-audio': 50,
    'cast': 51,
    'radio': 52,
    'fireplace': 53,
    'arrow-left-bold': 54,
    'arrow-right-bold': 55,
}

def get_icon_id(ma_name):
    if ma_name in icons:
        return icons[ma_name]
    else:
        return icons["alert-circle-outline"]
    