translations = {
    'af_ZA': {
        'ACTIVATE': "Aktiveer",
        'aux_heat': "Aanvullende hitte",
        'cooling': "Koel Af",
        'drying': "Droog Uit",
        'fan': "Waaier",
        'idle': "Onaktief",
        'off': "Af",
    },
    'ca_ES': {
        'PRESS': "Prem",
        'ACTIVATE': "Activar",
        'aux_heat': "Calefactor auxiliar",
        'cooling': "Refredant",
        'drying': "Assecant",
        'fan': "Ventilació",
        'idle': "Inactiu",
        'off': "OFF",
    },
    'cs_CZ': {
        'PRESS': "Stisknutí",
        'ACTIVATE': "Aktivovat",
        'aux_heat': "Pomocné teplo",
        'cooling': "Chlazení",
        'drying': "Sušení",
        'fan': "Ventilátor",
        'idle': "Nečinný",
        'off': "Vypnuto",
    },
    'cy_GB': {
        'ACTIVATE': "Actifadu",
        'off': "I ffwrdd",
    },
    'da_DK': {
        'PRESS': "Tryk",
        'ACTIVATE': "Aktiver",
        'aux_heat': "Støtte-varme",
        'cooling': "Køling",
        'drying': "Tørring",
        'fan': "Blæser",
        'idle': "Inaktiv",
        'off': "Fra",
    },
    'de_DE': {
        'PRESS': "Drücken",
        'ACTIVATE': "Aktivieren",
        'aux_heat': "Hilfswärme",
        'cooling': "Kühlung",
        'drying': "Trocknen",
        'fan': "Ventilator",
        'idle': "Leerlauf",
        'off': "Aus",
    },
    'en_GB': {
    },
    'en_US': {
        'PRESS': "Press",
        'ACTIVATE': "Activate",
        'aux_heat': "Aux heat",
        'cooling': "Cooling",
        'drying': "Drying",
        'fan': "Fan",
        'idle': "Idle",
        'off': "Off",
    },
    'es_ES': {
        'PRESS': "Pulsa",
        'ACTIVATE': "Activar",
        'aux_heat': "Calor auxiliar",
        'cooling': "Enfriando",
        'drying': "Secando",
        'fan': "Ventilador",
        'idle': "Inactivo",
        'off': "Apagado",
    },
    'et_EE': {
        'PRESS': "Vajuta nuppu",
        'ACTIVATE': "Aktiveeri",
        'aux_heat': "Abiküte",
        'cooling': "Jahutamine",
        'drying': "Kuivatamine",
        'fan': "Ventilaator",
        'idle': "Ootel",
        'off': "Väljas",
    },
    'eu_ES': {
        'ACTIVATE': "Aktibatu",
        'off': "Itzalita",
    },
    'fi_FI': {
        'PRESS': "Paina",
        'ACTIVATE': "Aktivoi",
        'aux_heat': "Lisälämpö",
        'cooling': "Jäähdytys",
        'drying': "Kuivaus",
        'fan': "Tuuletin",
        'idle': "Lepotilassa",
        'off': "Pois",
    },
    'fr_FR': {
        'PRESS': "Appui",
        'ACTIVATE': "Activer",
        'aux_heat': "Chauffage d'appoint",
        'cooling': "Refroidissement",
        'drying': "Séchage",
        'fan': "Ventilateur",
        'idle': "Inactif",
        'off': "Off",
    },
    'fy_DE': {
        'off': "Út",
    },
    'gl_ES': {
        'off': "Apagado",
    },
    'hr_HR': {
        'ACTIVATE': "Aktivirati",
        'aux_heat': "Pomoćno grijanje",
        'cooling': "Hlađenje",
        'drying': "Sušenje",
        'fan': "Ventilator",
        'idle': "Neaktivan",
        'off': "Isključen",
    },
    'id_ID': {
        'PRESS': "Tekan",
        'ACTIVATE': "Aktifkan",
        'aux_heat': "Pemanasan tambahan",
        'cooling': "Mendinginkan",
        'drying': "Mengeringkan",
        'fan': "Kipas",
        'idle': "Diam",
        'off': "Mati",
    },
    'is_IS': {
        'PRESS': "Ýttu á",
        'ACTIVATE': "Virkja",
        'cooling': "Kæling",
        'drying': "Þurrkun",
        'fan': "Vifta",
        'idle': "Aðgerðalaus",
        'off': "Slökkt",
    },
    'it_IT': {
        'PRESS': "Premi",
        'ACTIVATE': "Attiva",
        'aux_heat': "Riscaldamento ausiliario",
        'cooling': "Raffreddamento",
        'drying': "Deumidificazione",
        'fan': "Ventilatore",
        'idle': "Inattivo",
        'off': "Spento",
    },
    'nl_NL': {
        'PRESS': "Klik",
        'ACTIVATE': "Activeren",
        'aux_heat': "Extra warmte",
        'cooling': "Koelen",
        'drying': "Ontvochtigen",
        'fan': "Ventilator",
        'idle': "Inactief",
        'off': "Uit",
    },
    'nn_NO': {
        'ACTIVATE': "Aktiver",
        'aux_heat': "Aux-varme",
        'cooling': "Nedkjøling",
        'drying': "Tørkar",
        'fan': "Vifte",
        'idle': "Tomgang",
        'off': "Av",
    },
    'pt_PT': {
        'PRESS': "Pressione",
        'ACTIVATE': "Ativar",
        'aux_heat': "Calor auxiliar",
        'cooling': "Resfriar",
        'drying': "Secagem",
        'fan': "Ventoinha",
        'idle': "Em espera",
        'off': "Desligado",
    },
    'sr_RS': {
        'PRESS': "Pritisnite taster",
        'ACTIVATE': "Aktiviraj",
        'off': "Isključen",
    },
    'sv_SE': {
        'PRESS': "Tryck",
        'ACTIVATE': "Aktivera",
        'aux_heat': "Underhållsvärme",
        'cooling': "Kyler",
        'drying': "Avfuktar",
        'fan': "Fläkt",
        'idle': "Inaktiv",
        'off': "Av",
    },
}

def get_translation(locale, input):
    if locale in translations:
        return translations.get(locale).get(input, input)
    else:
        return translations.get("en_US").get(input, input)
