translations = {
        'af': {
            'ACTIVATE': "Aktiveer",
            'aux_heat': "Aanvullende hitte",
            'away_mode': "Wegmodus",
            'cooling': "Koel Af",
            'drying': "Droog Uit",
            'fan': "Waaier",
            'idle': "Onaktief",
            'off': "Af",
            'arm_away': "Bewapen weg",
            'arm_custom_bypass': "Pasgemaakte omseil",
            'arm_home': "Bewapen Huis",
            'arm_night': "Nag alarm",
            'clear_code': "Maak skoon",
            'code': "Kode",
            'disarm': "Skakel Af",
            'run': "Hardloop",
            'lock': "Sluit toe",
            'unlock': "Sluit oop",
            'brightness': "Helderheid",
            'color_temperature': "Kleur temperatuur",
            'position': "Posisie",
            'state': "Toestand",
            'currently': "Tans",
            'operation': "Operasie",
            'fan_mode': "Waaier modus",
            'heating': "Verhit",
        },
        'ar': {
            'ACTIVATE': "تفعيل",
            'aux_heat': "حرارة Aux",
            'away_mode': "خارج المنزل",
            'cooling': "تبريد",
            'drying': "تجفيف",
            'fan': "مروحة",
            'idle': "خامل",
            'off': "مطفئ",
            'arm_away': "تفعيل خارج المنزل",
            'arm_custom_bypass': "تجاوز مخصص",
            'arm_home': "تفعيل في المنزل",
            'arm_night': "تفعيل بالليل",
            'clear_code': "مسح",
            'code': "الرمز",
            'disarm': "تعطيل",
            'run': "تشغيل",
            'lock': "قفل",
            'unlock': "فتح",
            'brightness': "السطوع",
            'color_temperature': "درجة حرارة اللون",
            'position': "موضع",
            'state': "الحالة",
            'currently': "حاليا",
            'operation': "الوضع",
            'fan_mode': "وضع المروحة",
            'heating': "تدفئة",
        },
        'bg': {
            'ACTIVATE': "Активирай",
            'aux_heat': "Помощен нагревател",
            'away_mode': "Режим на отсъствие",
            'cooling': "Охлаждане",
            'drying': "Изсушаване",
            'fan': "Вентилатор",
            'idle': "Неработещ",
            'off': "Изключен",
            'arm_away': "Под охрана",
            'arm_custom_bypass': "Потребителски байпас",
            'arm_home': "Под охрана - вкъщи",
            'arm_night': "Под охрана - нощ",
            'arm_vacation': "Под охрана - ваканция",
            'clear_code': "Изчистване",
            'code': "Код",
            'disarm': "Деактивирaне",
            'run': "Изпълни",
            'lock': "Заключване",
            'unlock': "Отключване",
            'brightness': "Яркост",
            'color_temperature': "Цветова температура",
            'position': "Позиция",
            'state': "Състояние",
            'currently': "В момента",
            'operation': "Режим",
            'fan_mode': "Режим на вентилатора",
            'heating': "Отопление",
        },
        'ca': {
            'PRESS': "Prem",
            'ACTIVATE': "Activar",
            'aux_heat': "Calefactor auxiliar",
            'away_mode': "Mode absent",
            'cooling': "Refredant",
            'drying': "Assecant",
            'fan': "Ventilació",
            'idle': "Inactiu",
            'off': "OFF",
            'arm_away': "Activar, fora",
            'arm_custom_bypass': "Bypass personalitzat",
            'arm_home': "Activar, a casa",
            'arm_night': "Activar, nocturn",
            'arm_vacation': "Activa en mode vacances",
            'clear_code': "Borrar",
            'code': "Codi",
            'disarm': "Desactivar",
            'run': "Executa",
            'lock': "Bloquejar",
            'unlock': "Desbloquejar",
            'brightness': "Brillantor",
            'color_temperature': "Temperatura de color",
            'position': "Posició",
            'state': "Estat",
            'currently': "Actual",
            'operation': "Funcionament",
            'fan_mode': "Velocitat ventilador",
            'heating': "Escalfant",
        },
        'cs': {
            'PRESS': "Stisknutí",
            'ACTIVATE': "Aktivovat",
            'aux_heat': "Pomocné teplo",
            'away_mode': "Úsporný režim",
            'cooling': "Chlazení",
            'drying': "Sušení",
            'fan': "Ventilátor",
            'idle': "Nečinný",
            'off': "Vypnuto",
            'arm_away': "Aktivovat režim nepřítomnost",
            'arm_custom_bypass': "Vlastní obejítí",
            'arm_home': "Aktivovat režim domov",
            'arm_night': "Aktivovat noční režim",
            'arm_vacation': "Aktivovat režim dovolená",
            'clear_code': "Zrušit",
            'code': "Kód",
            'disarm': "Odbezpečit",
            'run': "Spustit",
            'lock': "Zamknout",
            'unlock': "Odemknout",
            'brightness': "Jas",
            'color_temperature': "Teplota barvy",
            'position': "Pozice",
            'state': "Stav",
            'currently': "Aktuálně",
            'operation': "Provoz",
            'fan_mode': "Režim ventilátoru",
            'heating': "Topení",
        },
        'da': {
            'PRESS': "Tryk",
            'ACTIVATE': "Aktiver",
            'aux_heat': "Støtte-varme",
            'away_mode': "Ude af huset-modus",
            'cooling': "Køling",
            'drying': "Tørring",
            'fan': "Blæser",
            'idle': "Inaktiv",
            'off': "Fra",
            'arm_away': "Tilkobl ude",
            'arm_custom_bypass': "Brugerdefineret bypass",
            'arm_home': "Tilkobl hjemme",
            'arm_night': "Tilkoblet nat",
            'arm_vacation': "Tilkobl ferie",
            'clear_code': "Ryd",
            'code': "Kode",
            'disarm': "Frakobl",
            'run': "Kør",
            'lock': "Lås",
            'unlock': "Lås op",
            'brightness': "Lysstyrke",
            'color_temperature': "Farvetemperatur",
            'position': "Position",
            'state': "Tilstand",
            'currently': "Aktuelt",
            'operation': "Drifttype",
            'fan_mode': "Blæsertilstand",
            'heating': "Opvarmning",
        },
        'de': {
            'PRESS': "Drücken",
            'ACTIVATE': "Aktivieren",
            'aux_heat': "Hilfswärme",
            'away_mode': "Abwesenheitsmodus",
            'cooling': "Kühlung",
            'drying': "Trocknen",
            'fan': "Ventilator",
            'idle': "Leerlauf",
            'off': "Aus",
            'arm_away': "Aktivieren - Unterwegs",
            'arm_custom_bypass': "Benutzerdefinierter Bypass",
            'arm_home': "Aktivieren - Zuhause",
            'arm_night': "Aktivieren - Nacht",
            'arm_vacation': "Aktiviere Urlaub",
            'clear_code': "Löschen",
            'code': "Code",
            'disarm': "Deaktivieren",
            'run': "Ausführen",
            'lock': "Verriegeln",
            'unlock': "Entriegeln",
            'brightness': "Helligkeit",
            'color_temperature': "Farbtemperatur",
            'position': "Position",
            'state': "Zustand",
            'currently': "Aktuell",
            'operation': "Aktion",
            'fan_mode': "Ventilator-Modus",
            'heating': "Heizung",
        },
        'el': {
            'PRESS': "Πατήστε",
            'ACTIVATE': "Ενεργοποίηση",
            'aux_heat': "Βοηθητική θέρμανση",
            'away_mode': "Λειτουργία εκτός σπιτιού",
            'cooling': "Ψύξη",
            'drying': "Αφύγρανση",
            'fan': "Ανεμιστήρας",
            'idle': "Σε αδράνεια",
            'off': "Μη Ενεργό",
            'arm_away': "Οπλισμός εκτός",
            'arm_custom_bypass': "Προσαρμοσμένη παράκαμψη",
            'arm_home': "Οπλισμός εντός",
            'arm_night': "Οπλισμός νυκτός",
            'arm_vacation': "Οπλισμός διακοπών",
            'clear_code': "Καθαρισμός",
            'code': "Κωδικός",
            'disarm': "Αφοπλισμός",
            'run': "Εκτέλεση",
            'lock': "Κλείδωμα",
            'unlock': "Ξεκλείδωμα",
            'brightness': "Φωτεινότητα",
            'color_temperature': "Θερμοκρασία χρώματος",
            'position': "Θέση",
            'state': "Κατάσταση",
            'currently': "Αυτή τη στιγμή",
            'operation': "Λειτουργία",
            'fan_mode': "Λειτουργία ανεμιστήρα",
            'heating': "Θέρμανση",
        },
        'en': {
            'PRESS': "Press",
            'ACTIVATE': "Activate",
            'aux_heat': "Aux heat",
            'away_mode': "Away mode",
            'cooling': "Cooling",
            'drying': "Drying",
            'fan': "Fan",
            'idle': "Idle",
            'off': "Off",
            'arm_away': "Arm away",
            'arm_custom_bypass': "Custom bypass",
            'arm_home': "Arm home",
            'arm_night': "Arm night",
            'arm_vacation': "Arm vacation",
            'clear_code': "Clear",
            'code': "Code",
            'disarm': "Disarm",
            'run': "Run",
            'lock': "Lock",
            'unlock': "Unlock",
            'brightness': "Brightness",
            'color_temperature': "Color temperature",
            'position': "Position",
            'state': "State",
            'currently': "Currently",
            'operation': "Operation",
            'fan_mode': "Fan mode",
            'heating': "Heating",
        },
        'eo': {
            'cooling': "malvarmigo",
            'code': "Kodo",
            'state': "Stato",
            'heating': "hejtado",
        },
        'es': {
            'PRESS': "Pulsa",
            'ACTIVATE': "Activar",
            'aux_heat': "Calor auxiliar",
            'away_mode': "Fuera de casa",
            'cooling': "Enfriando",
            'drying': "Secando",
            'fan': "Ventilador",
            'idle': "Inactivo",
            'off': "Apagado",
            'arm_away': "Armar ausente",
            'arm_custom_bypass': "Bypass personalizada",
            'arm_home': "Armar en casa",
            'arm_night': "Armar noche",
            'arm_vacation': "Armar por vacaciones",
            'clear_code': "Limpiar",
            'code': "Código",
            'disarm': "Desarmar",
            'run': "Ejecutar",
            'lock': "Bloquear",
            'unlock': "Desbloquear",
            'brightness': "Brillo",
            'color_temperature': "Temperatura del color",
            'position': "Posición",
            'state': "Estado",
            'currently': "Actualmente",
            'operation': "Modo",
            'fan_mode': "Modo del ventilador",
            'heating': "Calentando",
        },
        'et': {
            'PRESS': "Vajuta nuppu",
            'ACTIVATE': "Aktiveeri",
            'aux_heat': "Abiküte",
            'away_mode': "Eemal",
            'cooling': "Jahutamine",
            'drying': "Kuivatamine",
            'fan': "Ventilaator",
            'idle': "Ootel",
            'off': "Väljas",
            'arm_away': "Valvesta eemal",
            'arm_custom_bypass': "Eranditega",
            'arm_home': "Valvesta kodus",
            'arm_night': "Valvesta öine",
            'arm_vacation': "Valvesta puhkuse režiimis",
            'clear_code': "Puhasta",
            'code': "Kood",
            'disarm': "Valvest maha",
            'run': "Käivita",
            'lock': "Lukusta",
            'unlock': "Ava",
            'brightness': "Heledus",
            'color_temperature': "Värvustemperatuur",
            'position': "Asend",
            'state': "Olek",
            'currently': "Hetkel",
            'operation': "Töörežiim",
            'fan_mode': "Ventilaatori režiim",
            'heating': "Küte",
        },
        'fa': {
            'ACTIVATE': "فعال سازی",
            'aux_heat': "Aux گرما",
            'away_mode': "حالت بیرون",
            'cooling': "خنک کننده",
            'drying': "خشك كردن",
            'fan': "فن",
            'idle': "بیکار",
            'off': "خاموش",
            'arm_away': "حفاظت بیرون",
            'arm_custom_bypass': "بایگانی سفارشی",
            'arm_home': "حفاظت خانه",
            'arm_night': "نوبت شب",
            'clear_code': "پاک کردن",
            'code': "کد",
            'disarm': "دزدگیر خاموش",
            'run': "اجرا",
            'lock': "قفل",
            'unlock': "باز کردن",
            'brightness': "روشنایی",
            'color_temperature': "دمای رنگ",
            'position': "موقعیت",
            'state': "حالت",
            'currently': "در حال حاضر",
            'operation': "عملیات",
            'fan_mode': "حالت فن",
            'heating': "گرمایش",
        },
        'fi': {
            'PRESS': "Paina",
            'ACTIVATE': "Aktivoi",
            'aux_heat': "Lisälämpö",
            'away_mode': "Poissa kotoa -tila",
            'cooling': "Jäähdytys",
            'drying': "Kuivaus",
            'fan': "Tuuletin",
            'idle': "Lepotilassa",
            'off': "Pois",
            'arm_away': "Viritä (poissa)",
            'arm_custom_bypass': "Mukautettu ohitus",
            'arm_home': "Viritä (kotona)",
            'arm_night': "Viritä yöksi",
            'arm_vacation': "Aktivoi lomatila",
            'clear_code': "Tyhjennä",
            'code': "Koodi",
            'disarm': "Poista hälytys",
            'run': "Suorita",
            'lock': "Lukitse",
            'unlock': "Avaa lukitus",
            'brightness': "Kirkkaus",
            'color_temperature': "Värilämpötila",
            'position': "Sijainti",
            'state': "Tila",
            'currently': "Tällä hetkellä",
            'operation': "Toiminto",
            'fan_mode': "Tuuletustila",
            'heating': "Lämmitys",
        },
        'fr': {
            'PRESS': "Appui",
            'ACTIVATE': "Activer",
            'aux_heat': "Chauffage d'appoint",
            'away_mode': "Mode \"Absent\"",
            'cooling': "Refroidissement",
            'drying': "Séchage",
            'fan': "Ventilateur",
            'idle': "Inactif",
            'off': "Off",
            'arm_away': "Armer (absent)",
            'arm_custom_bypass': "Bypass personnalisé",
            'arm_home': "Armer (présent)",
            'arm_night': "Armer nuit",
            'arm_vacation': "Armer vacances",
            'clear_code': "Effacer",
            'code': "Code",
            'disarm': "Désarmer",
            'run': "Exécuter",
            'lock': "Verrouiller",
            'unlock': "Déverrouiller",
            'brightness': "Luminosité",
            'color_temperature': "Température de couleur",
            'position': "Position",
            'state': "État",
            'currently': "Actuellement",
            'operation': "Opération",
            'fan_mode': "Mode de ventilation",
            'heating': "En chauffe",
        },
        'he': {
            'PRESS': "לחיצה",
            'ACTIVATE': "הפעל",
            'aux_heat': "מסייע חום",
            'away_mode': "מצב לא בבית",
            'cooling': "קירור",
            'drying': "מייבש",
            'fan': "מאוורר",
            'idle': "כבוי",
            'off': "מופסק",
            'arm_away': "דרוך לא בבית",
            'arm_custom_bypass': "מעקף מותאם אישית",
            'arm_home': "דרוך בבית",
            'arm_night': "דריכה לילית",
            'arm_vacation': "דריכה - חופשה",
            'clear_code': "נקה",
            'code': "קוד",
            'disarm': "לא דרוך",
            'run': "רוץ",
            'lock': "נעילה",
            'unlock': "ביטול נעילה",
            'brightness': "בהירות",
            'color_temperature': "טמפרטורת הצבע",
            'position': "מיקום",
            'state': "מצב",
            'currently': "כעת",
            'operation': "פעולה",
            'fan_mode': "מצב מאורר",
            'heating': "חימום",
        },
        'hr': {
            'ACTIVATE': "Aktivirati",
            'aux_heat': "Pomoćno grijanje",
            'away_mode': "Način rada: Odsutan",
            'cooling': "Hlađenje",
            'drying': "Sušenje",
            'fan': "Ventilator",
            'idle': "Neaktivan",
            'off': "Isključen",
            'arm_away': "Aktiviran odsutno",
            'arm_custom_bypass': "Prilagođena premosnica",
            'arm_home': "Aktiviran doma",
            'arm_night': "Aktiviran nočni",
            'clear_code': "Vedro",
            'code': "Kod",
            'disarm': "Deaktiviraj",
            'run': "Pokreni",
            'lock': "zaključati",
            'unlock': "Otključati",
            'brightness': "Svjetlina",
            'color_temperature': "Temperatura boje",
            'position': "Pozicija",
            'state': "Stanje",
            'currently': "Trenutno",
            'operation': "operacija",
            'fan_mode': "Način rada s ventilatorom",
            'heating': "Grijanje",
        },
        'hu': {
            'PRESS': "Gombnyomás",
            'ACTIVATE': "Aktiválás",
            'aux_heat': "Külső hőforrás",
            'away_mode': "Távol mód",
            'cooling': "Hűtés",
            'drying': "Párátlanítás",
            'fan': "Ventilátor",
            'idle': "Tétlen",
            'off': "Ki",
            'arm_away': "Élesít (távozás)",
            'arm_custom_bypass': "Egyéni áthidalás",
            'arm_home': "Élesít (otthon)",
            'arm_night': "Élesít (éjszakai)",
            'arm_vacation': "Élesítés (vakáció)",
            'clear_code': "Törlés",
            'code': "Kód",
            'disarm': "Hatástalanít",
            'run': "Futtatás",
            'lock': "Bezár",
            'unlock': "Kinyit",
            'brightness': "Fényerő",
            'color_temperature': "Színhőmérséklet",
            'position': "Pozíció",
            'state': "Állapot",
            'currently': "Jelenleg",
            'operation': "Működés",
            'fan_mode': "Ventilátor",
            'heating': "Fűtés",
        },
        'hy': {
            'ACTIVATE': "Ակտիվացնել",
            'aux_heat': "Aux ջերմությունը",
            'away_mode': "հեռու ռեժիմ",
            'cooling': "հովացում",
            'drying': "Չորացում",
            'fan': "Երկրպագու",
            'idle': "Պարապ",
            'off': "Անջատած",
            'arm_away': "Ձեռք բերեք",
            'arm_custom_bypass': "Պատվերով շրջանցիկ",
            'arm_home': "Arm տուն",
            'arm_night': "Զինել - Գիշերային ռեժիմ",
            'clear_code': "Մաքրել",
            'code': "Կոդ",
            'disarm': "Զինաթափել",
            'lock': "Կողպեք",
            'unlock': "Բացել",
            'brightness': "Պայծառություն",
            'color_temperature': "Գունային ջերմաստիճան",
            'position': "Դիրք",
            'state': "Պետություն",
            'currently': "Ներկայումս",
            'operation': "Գործողություն",
            'fan_mode': "Երկրպագուների ռեժիմ",
            'heating': "Տաքացում",
        },
        'id': {
            'PRESS': "Tekan",
            'ACTIVATE': "Aktifkan",
            'aux_heat': "Pemanasan tambahan",
            'away_mode': "Mode keluar rumah",
            'cooling': "Mendinginkan",
            'drying': "Mengeringkan",
            'fan': "Kipas",
            'idle': "Diam",
            'off': "Mati",
            'arm_away': "Aktifkan utk keluar",
            'arm_custom_bypass': "Diaktifkan khusus",
            'arm_home': "Aktifkan utk di rumah",
            'arm_night': "Aktifkan utk malam",
            'arm_vacation': "Aktifkan utk liburan",
            'clear_code': "Hapus",
            'code': "Kode",
            'disarm': "Nonaktifkan",
            'run': "Jalankan",
            'lock': "Kunci",
            'unlock': "Buka",
            'brightness': "Kecerahan",
            'color_temperature': "Temperatur warna",
            'position': "Posisi",
            'state': "Status",
            'currently': "Saat ini",
            'operation': "Operasi",
            'fan_mode': "Mode kipas",
            'heating': "Memanaskan",
        },
        'is': {
            'PRESS': "Ýttu á",
            'ACTIVATE': "Virkja",
            'away_mode': "Fjarverandi hamur",
            'cooling': "Kæling",
            'drying': "Þurrkun",
            'fan': "Vifta",
            'idle': "Aðgerðalaus",
            'off': "Slökkt",
            'arm_away': "Vörður úti",
            'arm_custom_bypass': "Sérsniðin hjáleið",
            'arm_home': "Vörður heima",
            'arm_night': "Vörður nótt",
            'arm_vacation': "Vörður frí",
            'clear_code': "Hreinsa",
            'code': "Kóði",
            'disarm': "Taka af verði",
            'run': "Keyra",
            'lock': "Læsa",
            'unlock': "Aflæsa",
            'brightness': "Birtustig",
            'color_temperature': "Litastig",
            'position': "Staðsetning",
            'state': "Staða",
            'currently': "Er núna",
            'operation': "Aðgerð",
            'fan_mode': "Viftuhamur",
            'heating': "Kynding",
        },
        'it': {
            'PRESS': "Premi",
            'ACTIVATE': "Attiva",
            'aux_heat': "Riscaldamento ausiliario",
            'away_mode': "Modalità assente",
            'cooling': "Raffreddamento",
            'drying': "Deumidificazione",
            'fan': "Ventilatore",
            'idle': "Inattivo",
            'off': "Spento",
            'arm_away': "Attiva fuori casa",
            'arm_custom_bypass': "Bypass personalizzato",
            'arm_home': "Attiva in casa",
            'arm_night': "Attiva notte",
            'arm_vacation': "Attiva in vacanza",
            'clear_code': "Canc",
            'code': "Codice",
            'disarm': "Disattiva",
            'run': "Esegui",
            'lock': "Blocca",
            'unlock': "Sblocca",
            'brightness': "Luminosità",
            'color_temperature': "Temperatura colore",
            'position': "Apertura",
            'state': "Stato",
            'currently': "Attualmente",
            'operation': "Operazione",
            'fan_mode': "Ventilazione",
            'heating': "Riscaldamento",
        },
        'lb': {
            'ACTIVATE': "Aktivéieren",
            'aux_heat': "Zousätzlech Heizung",
            'away_mode': "Modus Keen Doheem",
            'cooling': "Ofkillen",
            'drying': "Dréchnen",
            'fan': "Ventilator",
            'idle': "Waart",
            'off': "Aus",
            'arm_away': "Aktivéiert Ënnerwee",
            'arm_custom_bypass': "Personaliséierte Bypass",
            'arm_home': "Aktivéiert Doheem",
            'arm_night': "Aktivéiert Nuecht",
            'clear_code': "Kloer",
            'code': "Code",
            'disarm': "Desaktivéieren",
            'run': "Ausféieren",
            'lock': "Spären",
            'unlock': "Entspären",
            'brightness': "Hellegkeet",
            'color_temperature': "Faarf Temperatur",
            'position': "Positioun",
            'state': "Zoustand",
            'currently': "Momentan",
            'operation': "Aktioun",
            'fan_mode': "Ventilatioun Modus",
            'heating': "Hëtzen",
        },
        'lt': {
            'ACTIVATE': "Suaktyvinti",
            'away_mode': "Išvykimo režimas",
            'cooling': "Aušinimas",
            'drying': "Džiovinimas",
            'fan': "Ventiliatorius",
            'idle': "Laukimo režimas",
            'off': "Išjungta",
            'arm_away': "Išvykęs",
            'arm_custom_bypass': "Individualizuotas apėjimas",
            'arm_home': "Namų apsauga",
            'arm_night': "Naktinė apsauga",
            'clear_code': "Išvalyti",
            'code': "Kodas",
            'disarm': "Atrakinti",
            'run': "Paleisti",
            'lock': "Užrakinti",
            'unlock': "Atrakinti",
            'brightness': "Ryškumas",
            'color_temperature': "Spalvos temperatūra",
            'position': "Padėtis",
            'state': "Būsena",
            'currently': "Šiuo metu",
            'operation': "Operacija",
            'fan_mode': "Ventiliatoriaus režimas",
            'heating': "Šildymas",
        },
        'lv': {
            'ACTIVATE': "Aktivizēt",
            'aux_heat': "Ārējais sildītājs",
            'away_mode': "Prombūtnes režīms",
            'cooling': "Dzesēšana",
            'drying': "Žāvēšana",
            'fan': "Ventilators",
            'idle': "Dīkstāve",
            'off': "Izslēgts",
            'arm_away': "Prombūtnes režīms",
            'arm_custom_bypass': "Pielāgots apvedceļš",
            'arm_home': "Mājās režīms",
            'arm_night': "Pieslēgta uz nakti",
            'clear_code': "Notīrīt",
            'code': "Kods",
            'disarm': "Atslēgt",
            'lock': "Aizslēgt",
            'unlock': "Atslēgt",
            'brightness': "Spilgtums",
            'color_temperature': "Krāsu temperatūra",
            'position': "Pozīcija",
            'state': "Stāvoklis",
            'currently': "Pašlaik",
            'operation': "Darbība",
            'fan_mode': "Ventilatora režīms",
            'heating': "Sildīšana",
        },
        'nb': {
            'PRESS': "trykk",
            'ACTIVATE': "Aktiver",
            'aux_heat': "Aux varme",
            'away_mode': "Bortemodus",
            'cooling': "Kjøling",
            'drying': "Tørking",
            'fan': "Vifte",
            'idle': "Inaktiv",
            'off': "Av",
            'arm_away': "Aktiver borte",
            'arm_custom_bypass': "Tilpasset bypass",
            'arm_home': "Aktiver hjemme",
            'arm_night': "Aktiver natt",
            'arm_vacation': "Aktiver ferie",
            'clear_code': "Tøm",
            'code': "Kode",
            'disarm': "Deaktivere",
            'run': "Kjør",
            'lock': "Lås",
            'unlock': "Lås opp",
            'brightness': "Lysstyrke",
            'color_temperature': "Fargetemperatur",
            'position': "Posisjon",
            'state': "Tilstand",
            'currently': "Er nå",
            'operation': "Operasjon",
            'fan_mode': "Viftemodus",
            'heating': "Oppvarming",
        },
        'nl': {
            'PRESS': "Klik",
            'ACTIVATE': "Activeren",
            'aux_heat': "Extra warmte",
            'away_mode': "Afwezigheidsmodus",
            'cooling': "Koelen",
            'drying': "Ontvochtigen",
            'fan': "Ventilator",
            'idle': "Inactief",
            'off': "Uit",
            'arm_away': "Inschakelen voor vertrek",
            'arm_custom_bypass': "Inschakelen met overbrugging",
            'arm_home': "Inschakelen voor thuis",
            'arm_night': "Inschakelen voor 's nachts",
            'arm_vacation': "Inschakelen voor vakantie",
            'clear_code': "Wis",
            'code': "Code",
            'disarm': "Uitschakelen",
            'run': "Uitvoeren",
            'lock': "Vergrendelen",
            'unlock': "Ontgrendelen",
            'brightness': "Helderheid",
            'color_temperature': "Kleurtemperatuur",
            'position': "Positie",
            'state': "Staat",
            'currently': "Momenteel",
            'operation': "Werking",
            'fan_mode': "Ventilatormodus",
            'heating': "Verwarmen",
        },
        'nn': {
            'ACTIVATE': "Aktiver",
            'aux_heat': "Aux-varme",
            'away_mode': "Bortemodus",
            'cooling': "Nedkjøling",
            'drying': "Tørkar",
            'fan': "Vifte",
            'idle': "Tomgang",
            'off': "Av",
            'arm_away': "Bortemodus",
            'arm_custom_bypass': "Tilpassa bypass",
            'arm_home': "Heimemodus",
            'arm_night': "Aktiver natt",
            'arm_vacation': "Armert feriemodus",
            'clear_code': "Slett alt",
            'code': "Kode",
            'disarm': "Skru av",
            'run': "Køyr",
            'lock': "Lås",
            'unlock': "Lås opp",
            'brightness': "Lysstyrke",
            'color_temperature': "Fargetemperatur",
            'position': "Posisjon",
            'state': "Tilstand",
            'currently': "Akkurat no",
            'operation': "Operasjon",
            'fan_mode': "Viftemodus",
            'heating': "Oppvarming",
        },
        'pl': {
            'PRESS': "Naciśnij",
            'ACTIVATE': "Aktywuj",
            'aux_heat': "Zewnętrznie podłączone źródło",
            'away_mode': "Tryb poza domem",
            'cooling': "chłodzenie",
            'drying': "osuszanie",
            'fan': "wentylator",
            'idle': "nieaktywny",
            'off': "wył.",
            'arm_away': "Uzbrój (poza domem)",
            'arm_custom_bypass': "Niestandardowy bypass",
            'arm_home': "Uzbrój (w domu)",
            'arm_night': "Uzbrój (noc)",
            'arm_vacation': "Uzbrój (tryb wakacyjny)",
            'clear_code': "Wyczyść",
            'code': "Kod",
            'disarm': "Rozbrój",
            'run': "Uruchom",
            'lock': "Zablokuj",
            'unlock': "Odblokuj",
            'brightness': "Jasność",
            'color_temperature': "Temperatura barwy",
            'position': "Pozycja",
            'state': "Stan",
            'currently': "Obecnie",
            'operation': "Tryb pracy",
            'fan_mode': "Tryb nawiewu",
            'heating': "grzanie",
        },
        'pt': {
            'PRESS': "Pressione",
            'ACTIVATE': "Ativar",
            'aux_heat': "Calor auxiliar",
            'away_mode': "Modo ausente",
            'cooling': "Resfriar",
            'drying': "Secagem",
            'fan': "Ventoinha",
            'idle': "Em espera",
            'off': "Desligado",
            'arm_away': "Armado ausente",
            'arm_custom_bypass': "Desvio personalizado",
            'arm_home': "Armado casa",
            'arm_night': "Armado noite",
            'clear_code': "Apagar",
            'code': "Código",
            'disarm': "Desarmar",
            'run': "Executar",
            'lock': "Bloquear",
            'unlock': "Desbloquear",
            'brightness': "Brilho",
            'color_temperature': "Temperatura de cor",
            'position': "Posição",
            'state': "Estado",
            'currently': "Atualmente",
            'operation': "Operação",
            'fan_mode': "Modo ventilar",
            'heating': "Aquecimento",
        },
        'ro': {
            'ACTIVATE': "Activați",
            'aux_heat': "Încălzire auxiliară",
            'away_mode': "Mod plecat",
            'cooling': "Racește",
            'drying': "Usucă",
            'fan': "Ventilator",
            'idle': "Inactiv",
            'off': "Oprit",
            'arm_away': "Armat plecat",
            'arm_custom_bypass': "Bypass personalizat",
            'arm_home': "Armat acasă",
            'arm_night': "Armat noaptea",
            'arm_vacation': "Armat vacanță",
            'clear_code': "Şterge",
            'code': "Cod",
            'disarm': "Dezarmat",
            'run': "Rulați",
            'lock': "Blocat",
            'unlock': "Deblocare",
            'brightness': "Luminozitate",
            'color_temperature': "Temperatură de culoare",
            'position': "Poziţie",
            'state': "Status",
            'currently': "În prezent",
            'operation': "Operație",
            'fan_mode': "Mod ventilator",
            'heating': "Încălzește",
        },
        'ru': {
            'PRESS': "Нажать",
            'ACTIVATE': "Активировать",
            'aux_heat': "Дополнительный нагрев",
            'away_mode': "Режим \"не дома\"",
            'cooling': "Охлаждение",
            'drying': "Осушение",
            'fan': "Вентиляция",
            'idle': "Бездействие",
            'off': "Выключено",
            'arm_away': "Охрана (не дома)",
            'arm_custom_bypass': "Охрана с исключениями",
            'arm_home': "Охрана (дома)",
            'arm_night': "Охрана (ночь)",
            'arm_vacation': "Охрана (отпуск)",
            'clear_code': "Сброс",
            'code': "Код",
            'disarm': "Снять с охраны",
            'run': "Запустить",
            'lock': "Закрыть",
            'unlock': "Открыть",
            'brightness': "Яркость",
            'color_temperature': "Цветовая температура",
            'position': "Положение",
            'state': "Состояние",
            'currently': "Сейчас",
            'operation': "Режим работы",
            'fan_mode': "Режим вентиляции",
            'heating': "Обогрев",
        },
        'sk': {
            'ACTIVATE': "Aktivovať",
            'aux_heat': "Prídavné kúrenie",
            'away_mode': "Režim neprítomnosti",
            'cooling': "Chladenie",
            'drying': "Sušenie",
            'fan': "Ventilátor",
            'idle': "Nečinný",
            'off': "Vypnutý",
            'arm_away': "Zakódovať odchod",
            'arm_custom_bypass': "Prispôsobené vylúčenie",
            'arm_home': "Zakódovať doma",
            'arm_night': "Zakódovať na noc",
            'arm_vacation': "Zakódovať dovolenku",
            'clear_code': "Zrušiť",
            'code': "Kód",
            'disarm': "Odkódovať",
            'run': "Spustiť",
            'lock': "Zamknúť",
            'unlock': "Odomknúť",
            'brightness': "Jas",
            'color_temperature': "Teplota farby",
            'position': "Poloha",
            'state': "Stav",
            'currently': "Aktuálne",
            'operation': "Prevádzka",
            'fan_mode': "Režim ventilátora",
            'heating': "Kúrenie",
        },
        'sl': {
            'PRESS': "Pritisnite",
            'ACTIVATE': "Aktiviraj",
            'aux_heat': "Dodatna toplota",
            'away_mode': "Način odsotnosti",
            'cooling': "Hlajenje",
            'drying': "Sušenje",
            'fan': "Ventilator",
            'idle': "V pripravljenosti",
            'off': "Izključen",
            'arm_away': "Vklopi odsoten",
            'arm_custom_bypass': "Izjeme po meri",
            'arm_home': "Vklopi doma",
            'arm_night': "Vklopi nočni način",
            'clear_code': "Počisti",
            'code': "Koda",
            'disarm': "Izklopi",
            'run': "Poženi",
            'lock': "Zakleni",
            'unlock': "Odkleni",
            'brightness': "Svetlost",
            'color_temperature': "Temperatura barve",
            'position': "Položaj",
            'state': "Stanje",
            'currently': "Trenutno",
            'operation': "Delovanje",
            'fan_mode': "Način ventilatorja",
            'heating': "Ogrevanje",
        },
        'sv': {
            'PRESS': "Tryck",
            'ACTIVATE': "Aktivera",
            'aux_heat': "Underhållsvärme",
            'away_mode': "Bortaläge",
            'cooling': "Kyler",
            'drying': "Avfuktar",
            'fan': "Fläkt",
            'idle': "Inaktiv",
            'off': "Av",
            'arm_away': "Larma bortaläge",
            'arm_custom_bypass': "Larm förbikopplat",
            'arm_home': "Larma hemmaläge",
            'arm_night': "Larma nattläge",
            'arm_vacation': "Larma semesterläge",
            'clear_code': "Rensa",
            'code': "Kod",
            'disarm': "Larma från",
            'run': "Kör",
            'lock': "Lås",
            'unlock': "Lås upp",
            'brightness': "Ljusstyrka",
            'color_temperature': "Färgtemperatur",
            'position': "Position",
            'state': "Tillstånd",
            'currently': "Nuvarande",
            'operation': "Driftläge",
            'fan_mode': "Fläktläge",
            'heating': "Värmer",
        },
        'th': {
            'PRESS': "กด",
            'ACTIVATE': "กระตุ้น",
            'aux_heat': "ความร้อน Aux",
            'away_mode': "โหมดไม่อยู่บ้าน",
            'cooling': "โหมดเย็น",
            'drying': "โหมดแห้ง",
            'fan': "พัดลม",
            'idle': "ไม่ได้ใช้งาน",
            'off': "ปิด",
            'arm_away': "ล็อคแบบออกข้างนอก",
            'arm_custom_bypass': "ปล่อยผ่านตามที่กำหนด",
            'arm_home': "ล็อคแบบอยู่บ้าน",
            'arm_night': "เฝ้ายามกลางคืน",
            'clear_code': "ล้าง",
            'code': "รหัส",
            'disarm': "ปิดระบบสัญญาณกันขโมย",
            'lock': "ล็อค",
            'unlock': "ปลดล็อค",
            'brightness': "ความสว่าง",
            'color_temperature': "อุณหภูมิสี",
            'position': "ตำแหน่ง",
            'state': "สถานะ",
            'currently': "ในขณะนี้",
            'operation': "การทำงาน",
            'fan_mode': "โหมดของพัดลม",
            'heating': "โหมดอบอุ่น",
        },
        'tr': {
            'PRESS': "Basınız",
            'ACTIVATE': "Etkinleştir",
            'aux_heat': "Yardımcı ısı",
            'away_mode': "Dışarıda modu",
            'cooling': "Soğutma",
            'drying': "Kurutma",
            'fan': "Fan",
            'idle': "Boşta",
            'off': "Kapalı",
            'arm_away': "Dışarıda",
            'arm_custom_bypass': "Özel atlatma",
            'arm_home': "Evde",
            'arm_night': "Geceyi etkinleştir",
            'arm_vacation': "Dışarıda",
            'clear_code': "Temizle",
            'code': "Kod",
            'disarm': "Etkisiz hale getir",
            'run': "Çalıştır",
            'lock': "Kilitle",
            'unlock': "Kilidi aç",
            'brightness': "Parlaklık",
            'color_temperature': "Renk sıcaklığı",
            'position': "Pozisyon",
            'state': "Durum",
            'currently': "Şu an",
            'operation': "İşlem",
            'fan_mode': "Fan modu",
            'heating': "Isıtma",
        },
        'uk': {
            'PRESS': "Натисніть",
            'ACTIVATE': "Активувати",
            'aux_heat': "Додатковий нагрів",
            'away_mode': "Режим \"Не вдома\"",
            'cooling': "Охолодження",
            'drying': "Осушення",
            'fan': "Вентилятор",
            'idle': "Очікування",
            'off': "Вимкнено",
            'arm_away': "ARM AWAY",
            'arm_custom_bypass': "Охорона з винятками",
            'arm_home': "ARM HOME",
            'arm_night': "ARM NIGHT",
            'clear_code': "CLEAR",
            'code': "Код",
            'disarm': "DISARM",
            'run': "Запустити",
            'lock': "Блокувати",
            'unlock': "Розблокувати",
            'brightness': "Яскравість",
            'color_temperature': "Кольорова температура",
            'position': "Положення",
            'state': "Статус",
            'currently': "В даний час",
            'operation': "Режим",
            'fan_mode': "Режим вентиляції",
            'heating': "Нагрівання",
        },
        'vi': {
            'ACTIVATE': "Kích hoạt",
            'aux_heat': "Nhiệt phụ trợ",
            'away_mode': "Chế độ đi vắng",
            'cooling': "Làm mát",
            'drying': "Làm khô",
            'fan': "Quạt",
            'idle': "Nhàn rỗi",
            'off': "Tắt",
            'arm_away': "Đi vắng",
            'arm_custom_bypass': "Bỏ qua tùy chỉnh",
            'arm_home': "Ở nhà",
            'arm_night': "An ninh ban đêm",
            'clear_code': "Xóa",
            'code': "Mã số",
            'disarm': "Vô hiệu hoá",
            'run': "Chạy",
            'lock': "Khóa",
            'unlock': "Mở khóa",
            'brightness': "Độ sáng",
            'color_temperature': "Nhiệt độ màu",
            'position': "Vị trí",
            'state': "Trạng thái",
            'currently': "Hiện tại",
            'operation': "Chế độ hoạt động",
            'fan_mode': "Chế độ quạt",
            'heating': "Làm ấm",
        },
        'zh-Hans': {
            'PRESS': "按下",
            'ACTIVATE': "激活",
            'aux_heat': "辅热",
            'away_mode': "离开模式",
            'cooling': "制冷",
            'drying': "除湿",
            'fan': "送风",
            'idle': "空闲",
            'off': "关",
            'arm_away': "离家警戒",
            'arm_custom_bypass': "自定义略过条件",
            'arm_home': "在家警戒",
            'arm_night': "夜间警戒",
            'arm_vacation': "度假警戒",
            'clear_code': "清除",
            'code': "密码",
            'disarm': "解除警戒",
            'run': "运行",
            'lock': "锁定",
            'unlock': "解锁",
            'brightness': "亮度",
            'color_temperature': "色温",
            'position': "位置",
            'state': "状态",
            'currently': "当前",
            'operation': "运行模式",
            'fan_mode': "风速",
            'heating': "制热",
        },
        'zh-Hant': {
            'PRESS': "按下",
            'ACTIVATE': "啟用",
            'aux_heat': "輔助暖氣",
            'away_mode': "外出模式",
            'cooling': "冷氣",
            'drying': "除濕",
            'fan': "風速",
            'idle': "閒置",
            'off': "關閉",
            'arm_away': "離家警戒",
            'arm_custom_bypass': "警戒模式狀態",
            'arm_home': "在家警戒",
            'arm_night': "夜間警戒",
            'arm_vacation': "度假警戒",
            'clear_code': "清除",
            'code': "密碼",
            'disarm': "解除警戒",
            'run': "執行",
            'lock': "上鎖",
            'unlock': "解鎖",
            'brightness': "亮度",
            'color_temperature': "色溫",
            'position': "位置",
            'state': "狀態判斷",
            'currently': "目前狀態",
            'operation': "運轉模式",
            'fan_mode': "風速模式",
            'heating': "暖氣",
        },
}

def lookup(locale, inputstr):
    if locale in ["zh_CN", "zh_Hans_CN", "zh_Hans"]:
        locale = "zh-Hans"
    elif locale in ["zh_TW", "zh_Hant_TW", "zh_Hant"]:
        locale = "zh-Hant"
    else:
        locale = locale.split("_")[0]
    
    en_fallback_res = translations.get("en").get(inputstr, inputstr)
    if locale in translations:    
        return translations.get(locale).get(inputstr, en_fallback_res)
    else:
        return en_fallback_res

def get_translation(locale, inputstr):
    inputstr = inputstr.replace("heat", "heating").replace("dry", "drying").replace("cool", "cooling").replace("fan_only", "fan")
    if inputstr == "heating_cooling":
        return f'{lookup(locale, "heating")}/{lookup(locale, "cooling")}'
        
    return lookup(locale, inputstr)

