translations = {
        'af': {
            'ACTIVATE': "Aktiveer",
            'aux_heat': "Aanvullende hitte",
            'cooling': "Koel Af",
            'drying': "Droog Uit",
            'fan': "Waaier",
            'idle': "Onaktief",
            'off': "Af",
            'arm_away': "Bewapen weg",
            'arm_custom_bypass': "Pasgemaakte omseil",
            'arm_home': "Bewapen Huis",
            'arm_night': "Nag alarm",
            'clear_code': "Maak skoon",
            'code': "Kode",
            'disarm': "Skakel Af",
            'run': "Hardloop",
        },
        'ar': {
            'ACTIVATE': "تفعيل",
            'aux_heat': "حرارة Aux",
            'cooling': "تبريد",
            'drying': "تجفيف",
            'fan': "مروحة",
            'idle': "خامل",
            'off': "مطفئ",
            'arm_away': "تفعيل خارج المنزل",
            'arm_custom_bypass': "تجاوز مخصص",
            'arm_home': "تفعيل في المنزل",
            'arm_night': "تفعيل بالليل",
            'clear_code': "مسح",
            'code': "الرمز",
            'disarm': "تعطيل",
            'run': "تشغيل",
        },
        'bg': {
            'ACTIVATE': "Активирай",
            'aux_heat': "Помощен нагревател",
            'cooling': "Охлаждане",
            'drying': "Изсушаване",
            'fan': "Вентилатор",
            'idle': "Неработещ",
            'off': "Изключен",
            'arm_away': "Под охрана",
            'arm_custom_bypass': "Потребителски байпас",
            'arm_home': "Под охрана - вкъщи",
            'arm_night': "Под охрана - нощ",
            'arm_vacation': "Под охрана - ваканция",
            'clear_code': "Изчистване",
            'code': "Код",
            'disarm': "Деактивирaне",
            'run': "Изпълни",
        },
        'ca': {
            'PRESS': "Prem",
            'ACTIVATE': "Activar",
            'aux_heat': "Calefactor auxiliar",
            'cooling': "Refredant",
            'drying': "Assecant",
            'fan': "Ventilació",
            'idle': "Inactiu",
            'off': "OFF",
            'arm_away': "Activar, fora",
            'arm_custom_bypass': "Bypass personalitzat",
            'arm_home': "Activar, a casa",
            'arm_night': "Activar, nocturn",
            'arm_vacation': "Activa en mode vacances",
            'clear_code': "Borrar",
            'code': "Codi",
            'disarm': "Desactivar",
            'run': "Executa",
        },
        'cs': {
            'PRESS': "Stisknutí",
            'ACTIVATE': "Aktivovat",
            'aux_heat': "Pomocné teplo",
            'cooling': "Chlazení",
            'drying': "Sušení",
            'fan': "Ventilátor",
            'idle': "Nečinný",
            'off': "Vypnuto",
            'arm_away': "Aktivovat režim nepřítomnost",
            'arm_custom_bypass': "Vlastní obejítí",
            'arm_home': "Aktivovat režim domov",
            'arm_night': "Aktivovat noční režim",
            'arm_vacation': "Aktivovat režim dovolená",
            'clear_code': "Zrušit",
            'code': "Kód",
            'disarm': "Odbezpečit",
            'run': "Spustit",
        },
        'da': {
            'PRESS': "Tryk",
            'ACTIVATE': "Aktiver",
            'aux_heat': "Støtte-varme",
            'cooling': "Køling",
            'drying': "Tørring",
            'fan': "Blæser",
            'idle': "Inaktiv",
            'off': "Fra",
            'arm_away': "Tilkobl ude",
            'arm_custom_bypass': "Brugerdefineret bypass",
            'arm_home': "Tilkobl hjemme",
            'arm_night': "Tilkoblet nat",
            'arm_vacation': "Tilkobl ferie",
            'clear_code': "Ryd",
            'code': "Kode",
            'disarm': "Frakobl",
            'run': "Kør",
        },
        'de': {
            'PRESS': "Drücken",
            'ACTIVATE': "Aktivieren",
            'aux_heat': "Hilfswärme",
            'cooling': "Kühlung",
            'drying': "Trocknen",
            'fan': "Ventilator",
            'idle': "Leerlauf",
            'off': "Aus",
            'arm_away': "Aktivieren - Unterwegs",
            'arm_custom_bypass': "Benutzerdefinierter Bypass",
            'arm_home': "Aktivieren - Zuhause",
            'arm_night': "Aktivieren - Nacht",
            'arm_vacation': "Aktiviere Urlaub",
            'clear_code': "Löschen",
            'code': "Code",
            'disarm': "Deaktivieren",
            'run': "Ausführen",
        },
        'el': {
            'PRESS': "Πατήστε",
            'ACTIVATE': "Ενεργοποίηση",
            'aux_heat': "Βοηθητική θέρμανση",
            'cooling': "Ψύξη",
            'drying': "Αφύγρανση",
            'fan': "Ανεμιστήρας",
            'idle': "Σε αδράνεια",
            'off': "Μη Ενεργό",
            'arm_away': "Οπλισμός εκτός",
            'arm_custom_bypass': "Προσαρμοσμένη παράκαμψη",
            'arm_home': "Οπλισμός εντός",
            'arm_night': "Οπλισμός νυκτός",
            'arm_vacation': "Οπλισμός διακοπών",
            'clear_code': "Καθαρισμός",
            'code': "Κωδικός",
            'disarm': "Αφοπλισμός",
            'run': "Εκτέλεση",
        },
        'en': {
            'PRESS': "Press",
            'ACTIVATE': "Activate",
            'aux_heat': "Aux heat",
            'cooling': "Cooling",
            'drying': "Drying",
            'fan': "Fan",
            'idle': "Idle",
            'off': "Off",
            'arm_away': "Arm away",
            'arm_custom_bypass': "Custom bypass",
            'arm_home': "Arm home",
            'arm_night': "Arm night",
            'arm_vacation': "Arm vacation",
            'clear_code': "Clear",
            'code': "Code",
            'disarm': "Disarm",
            'run': "Run",
        },
        'es': {
            'PRESS': "Pulsa",
            'ACTIVATE': "Activar",
            'aux_heat': "Calor auxiliar",
            'cooling': "Enfriando",
            'drying': "Secando",
            'fan': "Ventilador",
            'idle': "Inactivo",
            'off': "Apagado",
            'arm_away': "Armar ausente",
            'arm_custom_bypass': "Bypass personalizada",
            'arm_home': "Armar en casa",
            'arm_night': "Armar noche",
            'arm_vacation': "Armar por vacaciones",
            'clear_code': "Limpiar",
            'code': "Código",
            'disarm': "Desarmar",
            'run': "Ejecutar",
        },
        'et': {
            'PRESS': "Vajuta nuppu",
            'ACTIVATE': "Aktiveeri",
            'aux_heat': "Abiküte",
            'cooling': "Jahutamine",
            'drying': "Kuivatamine",
            'fan': "Ventilaator",
            'idle': "Ootel",
            'off': "Väljas",
            'arm_away': "Valvesta eemal",
            'arm_custom_bypass': "Eranditega",
            'arm_home': "Valvesta kodus",
            'arm_night': "Valvesta öine",
            'arm_vacation': "Valvesta puhkuse režiimis",
            'clear_code': "Puhasta",
            'code': "Kood",
            'disarm': "Valvest maha",
            'run': "Käivita",
        },
        'fa': {
            'ACTIVATE': "فعال سازی",
            'aux_heat': "Aux گرما",
            'cooling': "خنک کننده",
            'drying': "خشك كردن",
            'fan': "فن",
            'idle': "بیکار",
            'off': "خاموش",
            'arm_away': "حفاظت بیرون",
            'arm_custom_bypass': "بایگانی سفارشی",
            'arm_home': "حفاظت خانه",
            'arm_night': "نوبت شب",
            'clear_code': "پاک کردن",
            'code': "کد",
            'disarm': "دزدگیر خاموش",
            'run': "اجرا",
        },
        'fi': {
            'PRESS': "Paina",
            'ACTIVATE': "Aktivoi",
            'aux_heat': "Lisälämpö",
            'cooling': "Jäähdytys",
            'drying': "Kuivaus",
            'fan': "Tuuletin",
            'idle': "Lepotilassa",
            'off': "Pois",
            'arm_away': "Viritä (poissa)",
            'arm_custom_bypass': "Mukautettu ohitus",
            'arm_home': "Viritä (kotona)",
            'arm_night': "Viritä yöksi",
            'arm_vacation': "Aktivoi lomatila",
            'clear_code': "Tyhjennä",
            'code': "Koodi",
            'disarm': "Poista hälytys",
            'run': "Suorita",
        },
        'fr': {
            'PRESS': "Appui",
            'ACTIVATE': "Activer",
            'aux_heat': "Chauffage d'appoint",
            'cooling': "Refroidissement",
            'drying': "Séchage",
            'fan': "Ventilateur",
            'idle': "Inactif",
            'off': "Off",
            'arm_away': "Armer (absent)",
            'arm_custom_bypass': "Bypass personnalisé",
            'arm_home': "Armer (présent)",
            'arm_night': "Armer nuit",
            'arm_vacation': "Armer vacances",
            'clear_code': "Effacer",
            'code': "Code",
            'disarm': "Désarmer",
            'run': "Exécuter",
        },
        'he': {
            'PRESS': "לחיצה",
            'ACTIVATE': "הפעל",
            'aux_heat': "מסייע חום",
            'cooling': "קירור",
            'drying': "מייבש",
            'fan': "מאוורר",
            'idle': "כבוי",
            'off': "מופסק",
            'arm_away': "דרוך לא בבית",
            'arm_custom_bypass': "מעקף מותאם אישית",
            'arm_home': "דרוך בבית",
            'arm_night': "דריכה לילית",
            'arm_vacation': "דריכה - חופשה",
            'clear_code': "נקה",
            'code': "קוד",
            'disarm': "לא דרוך",
            'run': "רוץ",
        },
        'hr': {
            'ACTIVATE': "Aktivirati",
            'aux_heat': "Pomoćno grijanje",
            'cooling': "Hlađenje",
            'drying': "Sušenje",
            'fan': "Ventilator",
            'idle': "Neaktivan",
            'off': "Isključen",
            'arm_away': "Aktiviran odsutno",
            'arm_custom_bypass': "Prilagođena premosnica",
            'arm_home': "Aktiviran doma",
            'arm_night': "Aktiviran nočni",
            'clear_code': "Vedro",
            'code': "Kod",
            'disarm': "Deaktiviraj",
            'run': "Pokreni",
        },
        'hu': {
            'PRESS': "Gombnyomás",
            'ACTIVATE': "Aktiválás",
            'aux_heat': "Külső hőforrás",
            'cooling': "Hűtés",
            'drying': "Párátlanítás",
            'fan': "Ventilátor",
            'idle': "Tétlen",
            'off': "Ki",
            'arm_away': "Élesít (távozás)",
            'arm_custom_bypass': "Egyéni áthidalás",
            'arm_home': "Élesít (otthon)",
            'arm_night': "Élesít (éjszakai)",
            'arm_vacation': "Élesítés (vakáció)",
            'clear_code': "Törlés",
            'code': "Kód",
            'disarm': "Hatástalanít",
            'run': "Futtatás",
        },
        'hy': {
            'ACTIVATE': "Ակտիվացնել",
            'aux_heat': "Aux ջերմությունը",
            'cooling': "հովացում",
            'drying': "Չորացում",
            'fan': "Երկրպագու",
            'idle': "Պարապ",
            'off': "Անջատած",
            'arm_away': "Ձեռք բերեք",
            'arm_custom_bypass': "Պատվերով շրջանցիկ",
            'arm_home': "Arm տուն",
            'arm_night': "Զինել - Գիշերային ռեժիմ",
            'clear_code': "Մաքրել",
            'code': "Կոդ",
            'disarm': "Զինաթափել",
        },
        'id': {
            'PRESS': "Tekan",
            'ACTIVATE': "Aktifkan",
            'aux_heat': "Pemanasan tambahan",
            'cooling': "Mendinginkan",
            'drying': "Mengeringkan",
            'fan': "Kipas",
            'idle': "Diam",
            'off': "Mati",
            'arm_away': "Aktifkan utk keluar",
            'arm_custom_bypass': "Diaktifkan khusus",
            'arm_home': "Aktifkan utk di rumah",
            'arm_night': "Aktifkan utk malam",
            'arm_vacation': "Aktifkan utk liburan",
            'clear_code': "Hapus",
            'code': "Kode",
            'disarm': "Nonaktifkan",
            'run': "Jalankan",
        },
        'is': {
            'PRESS': "Ýttu á",
            'ACTIVATE': "Virkja",
            'cooling': "Kæling",
            'drying': "Þurrkun",
            'fan': "Vifta",
            'idle': "Aðgerðalaus",
            'off': "Slökkt",
            'arm_away': "Vörður úti",
            'arm_custom_bypass': "Sérsniðin hjáleið",
            'arm_home': "Vörður heima",
            'arm_night': "Vörður nótt",
            'arm_vacation': "Vörður frí",
            'clear_code': "Hreinsa",
            'code': "Kóði",
            'disarm': "Taka af verði",
            'run': "Keyra",
        },
        'it': {
            'PRESS': "Premi",
            'ACTIVATE': "Attiva",
            'aux_heat': "Riscaldamento ausiliario",
            'cooling': "Raffreddamento",
            'drying': "Deumidificazione",
            'fan': "Ventilatore",
            'idle': "Inattivo",
            'off': "Spento",
            'arm_away': "Attiva fuori casa",
            'arm_custom_bypass': "Bypass personalizzato",
            'arm_home': "Attiva in casa",
            'arm_night': "Attiva notte",
            'arm_vacation': "Attiva in vacanza",
            'clear_code': "Canc",
            'code': "Codice",
            'disarm': "Disattiva",
            'run': "Esegui",
        },
        'lb': {
            'ACTIVATE': "Aktivéieren",
            'aux_heat': "Zousätzlech Heizung",
            'cooling': "Ofkillen",
            'drying': "Dréchnen",
            'fan': "Ventilator",
            'idle': "Waart",
            'off': "Aus",
            'arm_away': "Aktivéiert Ënnerwee",
            'arm_custom_bypass': "Personaliséierte Bypass",
            'arm_home': "Aktivéiert Doheem",
            'arm_night': "Aktivéiert Nuecht",
            'clear_code': "Kloer",
            'code': "Code",
            'disarm': "Desaktivéieren",
            'run': "Ausféieren",
        },
        'lt': {
            'ACTIVATE': "Suaktyvinti",
            'cooling': "Aušinimas",
            'drying': "Džiovinimas",
            'fan': "Ventiliatorius",
            'idle': "Laukimo režimas",
            'off': "Išjungta",
            'arm_away': "Išvykęs",
            'arm_custom_bypass': "Individualizuotas apėjimas",
            'arm_home': "Namų apsauga",
            'arm_night': "Naktinė apsauga",
            'clear_code': "Išvalyti",
            'code': "Kodas",
            'disarm': "Atrakinti",
            'run': "Paleisti",
        },
        'lv': {
            'ACTIVATE': "Aktivizēt",
            'aux_heat': "Ārējais sildītājs",
            'cooling': "Dzesēšana",
            'drying': "Žāvēšana",
            'fan': "Ventilators",
            'idle': "Dīkstāve",
            'off': "Izslēgts",
            'arm_away': "Prombūtnes režīms",
            'arm_custom_bypass': "Pielāgots apvedceļš",
            'arm_home': "Mājās režīms",
            'arm_night': "Pieslēgta uz nakti",
            'clear_code': "Notīrīt",
            'code': "Kods",
            'disarm': "Atslēgt",
        },
        'nb': {
            'PRESS': "trykk",
            'ACTIVATE': "Aktiver",
            'aux_heat': "Aux varme",
            'cooling': "Kjøling",
            'drying': "Tørking",
            'fan': "Vifte",
            'idle': "Inaktiv",
            'off': "Av",
            'arm_away': "Aktiver borte",
            'arm_custom_bypass': "Tilpasset bypass",
            'arm_home': "Aktiver hjemme",
            'arm_night': "Aktiver natt",
            'arm_vacation': "Aktiver ferie",
            'clear_code': "Tøm",
            'code': "Kode",
            'disarm': "Deaktivere",
            'run': "Kjør",
        },
        'nl': {
            'PRESS': "Klik",
            'ACTIVATE': "Activeren",
            'aux_heat': "Extra warmte",
            'cooling': "Koelen",
            'drying': "Ontvochtigen",
            'fan': "Ventilator",
            'idle': "Inactief",
            'off': "Uit",
            'arm_away': "Inschakelen voor vertrek",
            'arm_custom_bypass': "Inschakelen met overbrugging",
            'arm_home': "Inschakelen voor thuis",
            'arm_night': "Inschakelen voor 's nachts",
            'arm_vacation': "Inschakelen voor vakantie",
            'clear_code': "Wis",
            'code': "Code",
            'disarm': "Uitschakelen",
            'run': "Uitvoeren",
        },
        'nn': {
            'ACTIVATE': "Aktiver",
            'aux_heat': "Aux-varme",
            'cooling': "Nedkjøling",
            'drying': "Tørkar",
            'fan': "Vifte",
            'idle': "Tomgang",
            'off': "Av",
            'arm_away': "Bortemodus",
            'arm_custom_bypass': "Tilpassa bypass",
            'arm_home': "Heimemodus",
            'arm_night': "Aktiver natt",
            'arm_vacation': "Armert feriemodus",
            'clear_code': "Slett alt",
            'code': "Kode",
            'disarm': "Skru av",
            'run': "Køyr",
        },
        'pl': {
            'PRESS': "Naciśnij",
            'ACTIVATE': "Aktywuj",
            'aux_heat': "Zewnętrznie podłączone źródło",
            'cooling': "chłodzenie",
            'drying': "osuszanie",
            'fan': "wentylator",
            'idle': "nieaktywny",
            'off': "wył.",
            'arm_away': "Uzbrój (poza domem)",
            'arm_custom_bypass': "Niestandardowy bypass",
            'arm_home': "Uzbrój (w domu)",
            'arm_night': "Uzbrój (noc)",
            'arm_vacation': "Uzbrój (tryb wakacyjny)",
            'clear_code': "Wyczyść",
            'code': "Kod",
            'disarm': "Rozbrój",
            'run': "Uruchom",
        },
        'pt': {
            'PRESS': "Pressione",
            'ACTIVATE': "Ativar",
            'aux_heat': "Aquecedor aux",
            'cooling': "Resfriando",
            'drying': "Secando",
            'fan': "Ventilando",
            'idle': "Oscioso",
            'off': "Desligado",
            'arm_away': "Armar ausente",
            'arm_custom_bypass': "Bypass personalizado",
            'arm_home': "Armar em casa",
            'arm_night': "Acionamento noturno",
            'arm_vacation': "Armar férias",
            'clear_code': "Limpar",
            'code': "Código",
            'disarm': "Desarmar",
            'run': "Executar",
        },
        'pt': {
            'PRESS': "Pressione",
            'ACTIVATE': "Ativar",
            'aux_heat': "Calor auxiliar",
            'cooling': "Resfriar",
            'drying': "Secagem",
            'fan': "Ventoinha",
            'idle': "Em espera",
            'off': "Desligado",
            'arm_away': "Armado ausente",
            'arm_custom_bypass': "Desvio personalizado",
            'arm_home': "Armado casa",
            'arm_night': "Armado noite",
            'clear_code': "Apagar",
            'code': "Código",
            'disarm': "Desarmar",
            'run': "Executar",
        },
        'ro': {
            'ACTIVATE': "Activați",
            'aux_heat': "Încălzire auxiliară",
            'cooling': "Racește",
            'drying': "Usucă",
            'fan': "Ventilator",
            'idle': "Inactiv",
            'off': "Oprit",
            'arm_away': "Armat plecat",
            'arm_custom_bypass': "Bypass personalizat",
            'arm_home': "Armat acasă",
            'arm_night': "Armat noaptea",
            'arm_vacation': "Armat vacanță",
            'clear_code': "Şterge",
            'code': "Cod",
            'disarm': "Dezarmat",
            'run': "Rulați",
        },
        'ru': {
            'PRESS': "Нажать",
            'ACTIVATE': "Активировать",
            'aux_heat': "Дополнительный нагрев",
            'cooling': "Охлаждение",
            'drying': "Осушение",
            'fan': "Вентиляция",
            'idle': "Бездействие",
            'off': "Выключено",
            'arm_away': "Охрана (не дома)",
            'arm_custom_bypass': "Охрана с исключениями",
            'arm_home': "Охрана (дома)",
            'arm_night': "Охрана (ночь)",
            'arm_vacation': "Охрана (отпуск)",
            'clear_code': "Сброс",
            'code': "Код",
            'disarm': "Снять с охраны",
            'run': "Запустить",
        },
        'sk': {
            'ACTIVATE': "Aktivovať",
            'aux_heat': "Prídavné kúrenie",
            'cooling': "Chladenie",
            'drying': "Sušenie",
            'fan': "Ventilátor",
            'idle': "Nečinný",
            'off': "Vypnutý",
            'arm_away': "Zakódovať odchod",
            'arm_custom_bypass': "Prispôsobené vylúčenie",
            'arm_home': "Zakódovať doma",
            'arm_night': "Zakódovať na noc",
            'arm_vacation': "Zakódovať dovolenku",
            'clear_code': "Zrušiť",
            'code': "Kód",
            'disarm': "Odkódovať",
            'run': "Spustiť",
        },
        'sl': {
            'PRESS': "Pritisnite",
            'ACTIVATE': "Aktiviraj",
            'aux_heat': "Dodatna toplota",
            'cooling': "Hlajenje",
            'drying': "Sušenje",
            'fan': "Ventilator",
            'idle': "V pripravljenosti",
            'off': "Izključen",
            'arm_away': "Vklopi odsoten",
            'arm_custom_bypass': "Izjeme po meri",
            'arm_home': "Vklopi doma",
            'arm_night': "Vklopi nočni način",
            'clear_code': "Počisti",
            'code': "Koda",
            'disarm': "Izklopi",
            'run': "Poženi",
        },
        'sv': {
            'PRESS': "Tryck",
            'ACTIVATE': "Aktivera",
            'aux_heat': "Underhållsvärme",
            'cooling': "Kyler",
            'drying': "Avfuktar",
            'fan': "Fläkt",
            'idle': "Inaktiv",
            'off': "Av",
            'arm_away': "Larma bortaläge",
            'arm_custom_bypass': "Larm förbikopplat",
            'arm_home': "Larma hemmaläge",
            'arm_night': "Larma nattläge",
            'arm_vacation': "Larma semesterläge",
            'clear_code': "Rensa",
            'code': "Kod",
            'disarm': "Larma från",
            'run': "Kör",
        },
        'th': {
            'PRESS': "กด",
            'ACTIVATE': "กระตุ้น",
            'aux_heat': "ความร้อน Aux",
            'cooling': "โหมดเย็น",
            'drying': "โหมดแห้ง",
            'fan': "พัดลม",
            'idle': "ไม่ได้ใช้งาน",
            'off': "ปิด",
            'arm_away': "ล็อคแบบออกข้างนอก",
            'arm_custom_bypass': "ปล่อยผ่านตามที่กำหนด",
            'arm_home': "ล็อคแบบอยู่บ้าน",
            'arm_night': "เฝ้ายามกลางคืน",
            'clear_code': "ล้าง",
            'code': "รหัส",
            'disarm': "ปิดระบบสัญญาณกันขโมย",
        },
        'tr': {
            'PRESS': "Basınız",
            'ACTIVATE': "Etkinleştir",
            'aux_heat': "Yardımcı ısı",
            'cooling': "Soğutma",
            'drying': "Kurutma",
            'fan': "Fan",
            'idle': "Boşta",
            'off': "Kapalı",
            'arm_away': "Dışarıda",
            'arm_custom_bypass': "Özel atlatma",
            'arm_home': "Evde",
            'arm_night': "Geceyi etkinleştir",
            'arm_vacation': "Dışarıda",
            'clear_code': "Temizle",
            'code': "Kod",
            'disarm': "Etkisiz hale getir",
            'run': "Çalıştır",
        },
        'uk': {
            'PRESS': "Натисніть",
            'ACTIVATE': "Активувати",
            'aux_heat': "Додатковий нагрів",
            'cooling': "Охолодження",
            'drying': "Осушення",
            'fan': "Вентилятор",
            'idle': "Очікування",
            'off': "Вимкнено",
            'arm_away': "ARM AWAY",
            'arm_custom_bypass': "Охорона з винятками",
            'arm_home': "ARM HOME",
            'arm_night': "ARM NIGHT",
            'clear_code': "CLEAR",
            'code': "Код",
            'disarm': "DISARM",
            'run': "Запустити",
        },
        'vi': {
            'ACTIVATE': "Kích hoạt",
            'aux_heat': "Nhiệt phụ trợ",
            'cooling': "Làm mát",
            'drying': "Làm khô",
            'fan': "Quạt",
            'idle': "Nhàn rỗi",
            'off': "Tắt",
            'arm_away': "Đi vắng",
            'arm_custom_bypass': "Bỏ qua tùy chỉnh",
            'arm_home': "Ở nhà",
            'arm_night': "An ninh ban đêm",
            'clear_code': "Xóa",
            'code': "Mã số",
            'disarm': "Vô hiệu hoá",
            'run': "Chạy",
        },
}

def get_translation(locale, input):
    locale = locale.split("_")[0]
    en_fallback_res = translations.get("en").get(input, input)
    if locale in translations:
        return translations.get(locale).get(input, en_fallback_res)
    else:
        return en_fallback_res
