# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/hassio-addons/base-python/aarch64:12.0.2"
  amd64: "ghcr.io/hassio-addons/base-python/amd64:12.0.2"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: NSPanel Lovelace UI"
  org.opencontainers.image.description: ""
  org.opencontainers.image.source: "https://github.com/bernadoDavinci/nspanel-lovelace-ui"
